const vocabZhishi = {
  id: 'vocab-zhishi-3-1',
  title: '字彙字識 3-1',
  subtitle: '第 3–2 單元 · 人物與職業',
  records: [
    ['v31-01','accountant','/əˈkaʊntənt/','n. (C)','會計師','Every business needs a good accountant to take care of its finances.','各行各業都需要優秀的會計師處理帳務。'],
    ['v31-02','addict','/ˈædɪkt/','n. (C)','入迷的人；成癮的人','The social worker helps drug addicts get back to a normal life.','這位社工幫助毒癮者重返正常生活。'],
    ['v31-03','agent','/ˈeɪdʒənt/','n. (C)','經紀人；代理人','The actress doesn’t have an agent, so she has to look for work herself.','這位女演員沒有經紀人，所以她得自己找工作。'],
    ['v31-04','amateur','/ˈæmətər/','n. (C)','業餘選手','Although he is only an amateur, he plays tennis very well.','雖然他只是業餘選手，網球卻打得很好。'],
    ['v31-05','ambassador','/æmˈbæsədər/','n. (C)','大使','The ambassador will attend the dinner party tomorrow evening.','這位大使明天晚上將出席晚宴。'],
    ['v31-06','ancestor','/ˈænsestər/','n. (C)','祖先','My ancestors came from China hundreds of years ago.','我的祖先幾百年前來自中國。'],
    ['v31-07','adviser','/ədˈvaɪzər/','n. (C)','顧問；指導老師','You should ask your business adviser for advice before making a decision.','你做決定前應該先請教商業顧問。'],
    ['v31-08','applicant','/ˈæplɪkənt/','n. (C)','申請者；應徵者','There were more than one hundred applicants for the job.','有超過一百人應徵這份工作。'],
    ['v31-09','assistant','/əˈsɪstənt/','n. (C)','助手；助理','The manager’s assistant answered the phone for him.','經理的助理替他接電話。'],
    ['v31-10','athlete','/ˈæθliːt/','n. (C)','運動員','The athlete won three gold medals at the Olympics.','這位運動員在奧運贏得三面金牌。'],
    ['v31-11a','athletic','/æθˈletɪk/','adj.','運動的；體育的','The school has many athletic activities for students.','這所學校有許多學生體育活動。'],
    ['v31-11b','athletic','/æθˈletɪk/','adj.','健壯的；擅長運動的','My brother is very athletic and enjoys playing basketball.','我哥哥很健壯，也喜歡打籃球。'],
    ['v31-12','banker','/ˈbæŋkər/','n. (C)','銀行家','Her father is a banker, and he works at a local bank.','她的父親是銀行家，在一家地方銀行工作。'],
    ['v31-13','beggar','/ˈbeɡər/','n. (C)','乞丐','The beggar asked people for money on the street.','那位乞丐在街上向人要錢。'],
    ['v31-14','bride','/braɪd/','n. (C)','新娘','The bride wore a beautiful white dress at her wedding.','新娘在婚禮上穿著一件漂亮的白色禮服。'],
    ['v31-15','bridegroom','/ˈbraɪdɡruːm/','n. (C)','新郎','The bridegroom waited nervously for the bride to arrive.','新郎緊張地等待新娘到來。'],
    ['v31-16','burglar','/ˈbɜːrɡlər/','n. (C)','竊賊；夜賊','The burglar broke into the house through a window.','竊賊從窗戶闖進屋裡。'],
    ['v31-17','candidate','/ˈkændɪdeɪt/','n. (C)','候選人；申請者','There are three candidates for the position.','有三位候選人競爭這個職位。'],
    ['v31-18','capitalist','/ˈkæpɪtəlɪst/','n. (C)','資本家','The capitalist invested a lot of money in the new company.','這位資本家投資了許多錢給這家新公司。'],
    ['v31-19','captain','/ˈkæptɪn/','n. (C)','隊長；船長；機長','The captain led the team to victory.','隊長帶領球隊獲勝。'],
    ['v31-20','carpenter','/ˈkɑːrpəntər/','n. (C)','木匠','The carpenter made a table out of wood.','這位木匠用木頭做了一張桌子。'],
    ['v31-21a','carrier','/ˈkæriər/','n. (C)','運輸公司；航空公司','Which carrier did you fly with?','你搭乘哪一家航空公司的班機？'],
    ['v31-21b','carrier','/ˈkæriər/','n. (C)','帶菌者；帶原者','Mosquitoes are carriers of many diseases.','蚊子是許多疾病的帶原者。'],
    ['v31-22','champion','/ˈtʃæmpiən/','n. (C)','冠軍','She became the tennis champion last year.','她去年成為網球冠軍。'],
    ['v31-23','citizen','/ˈsɪtɪzən/','n. (C)','公民；市民','Every citizen has the right to vote.','每位公民都有投票權。'],
    ['v31-24a','civilian','/səˈvɪliən/','n. (C)','平民','Many civilians were hurt during the war.','許多平民在戰爭中受傷。'],
    ['v31-24b','civilian','/səˈvɪliən/','adj.','平民的；非軍用的','The airport is used for civilian purposes.','這座機場供民用。'],
    ['v31-25a','cleaner','/ˈkliːnər/','n. (C)','清潔工','The cleaner comes to the office every morning.','清潔工每天早晨來辦公室。'],
    ['v31-25b','cleaner','/ˈkliːnər/','n. (U)','清潔劑','Keep the cleaner away from children.','請將清潔劑放在孩童拿不到的地方。'],
    ['v31-26','client','/ˈklaɪənt/','n. (C)','客戶；委託人','The lawyer met with her client this morning.','這位律師今早與她的委託人會面。'],
    ['v31-27','clown','/klaʊn/','n. (C)','小丑','The clown made the children laugh.','小丑逗得孩子們哈哈大笑。'],
    ['v31-28a','coach','/koʊtʃ/','n. (C)','教練','Our coach taught us how to work as a team.','我們的教練教我們如何團隊合作。'],
    ['v31-28b','coach','/koʊtʃ/','v.','訓練；指導','My father coached me for the speech contest.','我父親指導我準備演講比賽。'],
    ['v31-29','colleague','/ˈkɑːliːɡ/','n. (C)','同事','I had lunch with two colleagues from work.','我和兩位同事一起吃午餐。'],
    ['v31-30','commander','/kəˈmændər/','n. (C)','指揮官；司令','The commander gave the soldiers an order.','指揮官給士兵下了一道命令。'],
    ['v31-31','competitor','/kəmˈpetɪtər/','n. (C)','競爭者；參賽者','There were twenty competitors in the race.','這場比賽有二十名參賽者。'],
    ['v31-32','composer','/kəmˈpoʊzər/','n. (C)','作曲家','Mozart was a famous composer.','莫札特是一位著名的作曲家。'],
    ['v31-33a','conductor','/kənˈdʌktər/','n. (C)','指揮家','The conductor raised his hands, and the concert began.','指揮家舉起雙手，音樂會便開始了。'],
    ['v31-33b','conductor','/kənˈdʌktər/','n. (C)','導體','Copper is a good conductor of electricity.','銅是良好的電導體。'],
    ['v31-34','consultant','/kənˈsʌltənt/','n. (C)','顧問','The company hired a consultant to solve the problem.','這家公司聘請顧問來解決問題。'],
    ['v31-35','consumer','/kənˈsuːmər/','n. (C)','消費者','The new law protects consumers’ rights.','這項新法律保護消費者的權益。'],
    ['v31-36','controller','/kənˈtroʊlər/','n. (C)','控制器；管理員','Use the controller to change the temperature.','使用控制器來改變溫度。'],
    ['v31-37','coward','/ˈkaʊərd/','n. (C)','膽小鬼','Don’t be a coward. Tell the truth.','別當膽小鬼，說出真相。'],
    ['v31-38','creator','/kriˈeɪtər/','n. (C)','創造者；創作者','The creator of the show is very talented.','這個節目的創作者很有才華。'],
    ['v31-39a','criminal','/ˈkrɪmɪnəl/','n. (C)','罪犯','The police caught the criminal yesterday.','警方昨天逮捕了這名罪犯。'],
    ['v31-39b','criminal','/ˈkrɪmɪnəl/','adj.','犯罪的；刑事的','Stealing is a criminal act.','偷竊是犯罪行為。'],
    ['v31-40','critic','/ˈkrɪtɪk/','n. (C)','評論家；批評者','The movie received good reviews from critics.','這部電影獲得評論家的好評。'],
    ['v31-41','dealer','/ˈdiːlər/','n. (C)','經銷商；交易員','He is a car dealer in this town.','他是這個城鎮的汽車經銷商。'],
    ['v31-42','designer','/dɪˈzaɪnər/','n. (C)','設計師','The designer created a beautiful dress.','這位設計師設計了一件漂亮的洋裝。'],
    ['v31-43','detective','/dɪˈtektɪv/','n. (C)','偵探','The detective found an important clue.','這位偵探找到一條重要線索。'],
    ['v31-44','diplomat','/ˈdɪpləmæt/','n. (C)','外交官','The diplomat works to improve relations between countries.','這位外交官致力於改善國與國之間的關係。'],
    ['v31-45','economist','/ɪˈkɑːnəmɪst/','n. (C)','經濟學家','The economist talked about the country’s economy on TV.','這位經濟學家在電視上談論國家經濟。'],
    ['v31-46','editor','/ˈedɪtər/','n. (C)','編輯','The editor checked the article before it was published.','編輯在文章出版前檢查了內容。'],
    ['v31-47','embassy','/ˈembəsi/','n. (C)','大使館','We went to the embassy to apply for a visa.','我們到大使館申請簽證。']
  ].map(([id, word, phonetic, pos, meaning, example, translation]) => ({ id, word, phonetic, pos, meaning, example, translation }))
};
